### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by o-moridon** [o-moridon/protospace-39741#1]
# URL
https://protospace-39741.onrender.com/

**Comment by mo1015** [comment]
@o-moridon さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
トップページに遷移してしまいます。投稿ページに留まるように修正しましょう。

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックした場合に遷移しないため、修正しましょう。

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること**
ログイン状態でも編集ページに遷移できません。（エラー画面に遷移します）

**※編集機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。**

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by o-moridon** [comment]
確認ありがとうございました。

投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること
トップページに遷移してしまいます。投稿ページに留まるように修正しましょう。
　＞　修正しました。
　
ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること
　＞　修正しました。
　
ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること
　＞　本番環境でuser_isが１だとエラーが出ませんでした。開発環境はどのidでも大丈夫だという不思議なエラーですね。。修正しました。
　
　本番環境も一通り確認しました。
　ご確認よろしくお願いします！

**Comment by shodai-ito** [comment]
@o-moridon さん、再度ご提出ありがとうございます‼︎
指摘内容の修正が確認できました！
引き続き動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **空の入力欄がある場合は、編集できずにそのページに留まること**
ページに留まらず、詳細ページに遷移してしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by o-moridon** [comment]
確認ありがとうございます。

修正いたしました。

**Comment by moom1122** [comment]
@o-moridon さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
